language: java
notifications:
  hipchat:
    rooms:
      secure: piRsdIga9kPUSVT49zzrGS2MTF7D508A0W141eJf0BSbkmJcBzTD9c5+BiBcoZBkx9w3Nj0fqfaPIV1EVo5azykAa7JcMxiRjLoxfkOzn2+YFaJnbIPNFrZPcda9NcZeyaOxMbjs8wCMLy3uIh65XagBVUbiIOGNnt4wxFkrTRY=
